# Generated by Django 5.1.4 on 2024-12-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candle", "0002_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="pinterest_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
