# Generated by Django 5.1.4 on 2024-12-30 23:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candle", "0005_alter_blogpost_thumbnail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ("-published_date",)},
        ),
        migrations.AlterModelOptions(
            name="candleworkshop",
            options={"ordering": ("-date",)},
        ),
    ]
