# Generated by Django 5.1.4 on 2024-12-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candle", "0006_alter_blogpost_options_alter_candleworkshop_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-booking_date"]},
        ),
        migrations.AddField(
            model_name="candleworkshop",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Featured image for the workshop",
                null=True,
                upload_to="workshop_thumbnails/",
            ),
        ),
    ]
