# Generated by Django 5.1.4 on 2024-12-31 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candle", "0007_alter_booking_options_candleworkshop_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="candleworkshop",
            name="duration",
            field=models.FloatField(
                default=1,
                help_text="Duration of the workshop in hours (e.g., 1.5 for 1.5 hours)",
            ),
            preserve_default=False,
        ),
    ]
