# Generated by Django 5.1.4 on 2024-12-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candle", "0008_candleworkshop_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=5),
        ),
    ]
