# Generated by Django 5.1.4 on 2024-12-31 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candle", "0012_alter_customuser_username"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
