# Generated by Django 5.1.4 on 2024-12-31 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0004_alter_logentry_user"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("candle", "0014_user_alter_blogpost_author_alter_booking_user_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="CustomUser",
        ),
    ]
