# Generated by Django 5.1.4 on 2024-12-31 07:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candle", "0015_rename_user_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
